### ISSUE TITLE
many issues with scopes

### ISSUE THREAD

**Issue by Un1q32** [MrCrayfish/MrCrayfishGunMod#308]
1: the long and medium scopes when not ads still displays what the gun is pointing at which is inaccurate
![2022-06-20_21 56 27](https://user-images.githubusercontent.com/57970114/174700414-d29d470c-3ae9-40dd-920a-9ca7a3227e45.png)

2: short scopes are broken when not ads (and slightly broken when ads)
![2022-06-20_21 57 50](https://user-images.githubusercontent.com/57970114/174701048-df234f7b-0cf3-4a6f-b01b-a26ed2b69a33.png)
![2022-06-20_22 11 45](https://user-images.githubusercontent.com/57970114/174701799-7c151c64-0762-4641-82d2-5b6ed9cb76db.png)

3: with the medium and long scopes, ~~(and probobly the short one too but it to subtle to notice)~~ (it does not happen with the short scope i was mistaken) the zoom in keeps the resolution of the area it zooms into, leading to low res. (most noticeable with long scope and optifine zoom on low res monitors)
![2022-06-20_22 04 14](https://user-images.githubusercontent.com/57970114/174701663-70af358a-6b6d-4156-8af7-d43bb5341ab8.png)
![2022-06-20_22 04 21](https://user-images.githubusercontent.com/57970114/174701666-6e89b442-8ac9-4abb-92f5-bb7081ff20a3.png)

**Comment by MrCrayfish** [comment]
For 1 and 3, those are related to performance. The world is not rendering again from it's point of view, so it just copies the render buffer of the world before the first person items are drawn. This means that scaling the image (show in pictrues 3) will have noticeable pixels. I can't fix without tanking the performance of everyones game.

2 is fixed in an upcoming update.
