### ISSUE TITLE
The scope shows shit with shaders.

### ISSUE THREAD

**Issue by KostromDan** [MrCrayfish/MrCrayfishGunMod#379]
https://user-images.githubusercontent.com/90044015/197581264-1547849c-06cf-4fc8-97c8-2730473fcefe.mp4

**Comment by KostromDan** [comment]
https://user-images.githubusercontent.com/90044015/197581904-1ed889a3-ade9-44a1-9618-a4794c094fbe.mp4

**Comment by MrCrayfish** [comment]
No, you have an additional mod or shader adding that idle motion effect.

**Comment by KostromDan** [comment]
> No, you have an additional mod or shader adding that idle motion effect.

Yes, i have and hand sway option in my shaders turned on, i disabled it, now 1x scopes work well, but other still show something not from our world.
https://youtu.be/9NnxGSoM4Ks

**Comment by robxxrrr** [comment]
i have te same problem, and with the same shaders too. Only that type of long scopes are the ones that shows that strange bloom effect. And its not problem of the mod, because when i turn off shaders, that weird effect dissapears.. I was trying to turn off reflections settings or ssao and a lot of options in the shader looking for the one that makes that but, no one of them was the cause of it. I dont know what is the problem and why only in that long scopes, anyone could help us?
![imagen_2022-11-05_141438133](https://user-images.githubusercontent.com/117521883/200121691-75cf4baa-3286-4a97-a4a6-f6f55512b068.png)
