### ISSUE TITLE
Stocks are no longer applicable to weapon

### ISSUE THREAD

**Issue by Autovw** [MrCrayfish/MrCrayfishGunMod#414]
I'm assuming this may have been added for debugging, but was left in by accident

https://github.com/MrCrayfish/MrCrayfishGunMod/blob/2259c035e0a1d1d379ddb114ce47846adaaae565/src/main/java/com/mrcrayfish/guns/item/StockItem.java#L45-L49

**Comment by zaeonNineZero** [comment]
Can confirm that in-game all guns cannot take stocks, including guns from my in-development addon.

Replacing StockItem.class in the jar file with the version of StockItem.class from 1.2.8 immediately fixes the bug, though it is a rather hacky solution. This is almost certainly because the 'canAttachTo' boolean is not present in StockItem.class in 1.2.8.

**Comment by Autovw** [comment]
The description I provided already explains the issue and what can be done about it to fix it by the author. :)

Your 'hacky solution' is a very bad practice and should never be done by anyone. If you want to change something in the mod you should do it in the original source code and not in the compiled jar.

**Comment by MrCrayfish** [comment]
My bad. I accidentally left this in as I was testing it for https://github.com/MrCrayfish/MrCrayfishGunMod/commit/e6a8a509f1dcce367087717193c196487a5925c6
