### ISSUE TITLE
Bug/Suggestion:  No way to change aim/shoot bindings?

### ISSUE THREAD

**Issue by Nyquil98** [MrCrayfish/MrCrayfishGunMod#459]
I play minecraft with the break/place buttons reversed from default, but I play FPS games with the default aim (RMB) and shoot (LMB). Is there a way to rebind the controls only for CGM and not all of minecraft? Cant find it in the configs or in game settings if its there.

**Comment by MrCrayfish** [comment]
I'll look into it when I update the mod to 1.19.4

**Comment by Jer6776** [comment]
is it possible to be added to 1.19.3?

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/MrCrayfishGunMod/commit/5acf008d1f1c37477294f351f9c1adb59bd2ea2a

Unfortunately due to technical reasons, you won't be able to use offhand items like a shield. This is not something that can be fixed, the gun mod is already performing lots of hacks to get the current control system working.
