### ISSUE TITLE
[Request/Suggestion] Add magazines, more refined gun animation

### ISSUE THREAD

**Issue by DaoHuang1** [MrCrayfish/MrCrayfishGunMod#486]
Hope to add magazines so that bullets don't take up inventory space.  I also hope that there can be more refined reloading animations, (such as using a magazine to reload) instead of directly stuffing bullets into the gun.And dual wielding guns

**Comment by Zanklev** [comment]
A magazine system with manual reloading and proper reload animations are my absolute dream for this mod.

**Comment by chemlzh** [comment]
> A magazine system with manual reloading and proper reload animations are my absolute dream for this mod.

I can't agree more. Also the damage system needs overwrite. Now the damage is based on gun data, not bullet data. So one kind of gun can only fire one kind of bullet. Using bullet type to calculate damage may fit more with magazine system, since you can fill the magazine with AP rounds and FMJ rounds of the same calibre.

However if magazine system is implemented, the over capacity enchantment needs overhaul, since gun capacity depends on magazine now. i don't know if MrCrayfish has much time to deal with it.

**Comment by MrCrayfish** [comment]
This mod was always intended to be simple, magazines are not going to be added. It may sound like a simple feature but in reality that means adding in a full animation system, reworking reloading system, and rebalancing all weapons. Not to mention, breaking every addon created for mod. TLDR lots of work. I've had thoughts about adding an ammo pouch, but that's about it so far.

There are already lots of alternative mods that you can use with those features. I am personally happy with the current state of the mod and it differentiating itself from others. In regards to @chemlzh post, ammo is again kept simple. If you want more damage or modifications, the enchantments have been designed to do that.
